### ISSUE TITLE
Releasing pre-trained models?

### ISSUE THREAD

**Issue by rkjones4** [SilenKZYoung/CuboidAbstractionViaSeg#1]
Hi -- awesome work!

I was just wondering if you were planning on releasing pre-trained models for any categories from ShapeNet? If you are, do you have any idea on when you might do so?

Thanks!

**Comment by SilenKZYoung** [comment]
Hi,
We have released our [Pretrain models](https://drive.google.com/file/d/1JQ0PC4cvHm_vELQbik1v9pErTVg9nxG6/view?usp=sharing).
Thank you for your interest!
