### ISSUE TITLE
Link of 'Dataset' is not shareable, Need Access

### ISSUE THREAD

**Issue by tommaoer** [SilenKZYoung/CuboidAbstractionViaSeg#2]
Hi, @SilenKZYoung 
Thanks for the great work. I am interested to try it and explorer more on this paper, but the link of [Dataset](https://drive.google.com/file/d/18ngs7hefXOptpuEHrLzeTUCT0Vn1Ou4l/view?usp=sharing) is not shareable, which needs access and I have requested(yj444757397@gmail).

Thanks & Regards,
Jie

**Comment by SilenKZYoung** [comment]
Hi, @tommaoer 
We have modified the link and now anyone could download the dataset.
Thank you for your interest!
